package compilador;

public enum TokenType {
    INT, STRING, FLOAT, CHAR,
    NUMINTEGER, NUMFLOAT, TEXTSTRING,
    IDENTIFIER, ASSIGN, PRINT, LOOP, IF, ELSE,
    SEMICOLON, OPENPARENTESE, CLOSEPARENTESE, MAIOR, MENOR, ASPASSIMPLES, OPENBRACE, CLOSEBRACE, INCREMENT
}
